// get all users.
export const GET_USERS_ACTION = 'GET_USERS_ACTION';
export const GET_USERS_SUCCESSFUL = 'GET_USERS_SUCCESSFUL';
export const GET_USERS_FAILED = 'GET_USERS_FAILED';

// send generic list of users
export const SEND_GENERIC_USERS_ACTION = 'SEND_GENERIC_USERS_ACTION';
export const SEND_GENERIC_USERS_SUCCESSFUL = 'SEND_GENERIC_USERS_SUCCESSFUL';
export const SEND_GENERIC_USERS_FAILED = 'SEND_GENERIC_USERS_FAILED';

// send sepecific list of users
export const SEND_SPECIFIC_USERS_ACTION = 'SEND_SPECIFIC_USERS_ACTION';
export const SEND_SPECIFIC_USERS_SUCCESSFUL = 'SEND_SPECIFIC_USERS_SUCCESSFUL';
export const SEND_SPECIFIC_USERS_FAILED = 'SEND_SPECIFIC_USERS_FAILED';

// add user to generic list
export const ADD_GENERIC_USER_ACTION = 'ADD_GENERIC_USER_ACTION';
export const ADD_GENERIC_USER_SUCCESSFUL = 'ADD_GENERIC_USER_SUCCESSFUL';
export const ADD_GENERIC_USER_FAILED = 'ADD_GENERIC_USER_FAILED';

// add user to generic list
export const ADD_SPECIFIC_USER_ACTION = 'ADD_SPECIFIC_USER_ACTION';
export const ADD_SPECIFIC_USER_SUCCESSFUL = 'ADD_SPECIFIC_USER_SUCCESSFUL';
export const ADD_SPECIFIC_USER_FAILED = 'ADD_SPECIFIC_USER_FAILED';
