// get all users.
export const GET_USERS_ACTION = 'GET_USERS_ACTION';
export const GET_USERS_SUCCESSFUL = 'GET_USERS_SUCCESSFUL';
export const GET_USERS_FAILED = 'GET_USERS_FAILED';

// send generic list of users
export const SEND_DATA_SORTED_BY_NAME_ACTION = 'SEND_DATA_SORTED_BY_NAME_ACTION';
export const SEND_DATA_SORTED_BY_NAME_SUCCESSFUL = 'SEND_DATA_SORTED_BY_NAME_SUCCESSFUL';
export const SEND_DATA_SORTED_BY_NAME_FAILED = 'SEND_DATA_SORTED_BY_NAME_FAILED';

// send sepecific list of users
export const SEND_DATA_SORTED_BY_AGE_ACTION = 'SEND_DATA_SORTED_BY_AGE_ACTION';
export const SEND_DATA_SORTED_BY_AGE_SUCCESSFUL = 'SEND_DATA_SORTED_BY_AGE_SUCCESSFUL';
export const SEND_DATA_SORTED_BY_AGE_FAILED = 'SEND_DATA_SORTED_BY_AGE_FAILED';

// add user to generic list
export const ADD_GENERIC_USER_ACTION = 'ADD_GENERIC_USER_ACTION';

// add user to generic list
export const ADD_SPECIFIC_USER_ACTION = 'ADD_SPECIFIC_USER_ACTION';

// remove user from generic list
export const REMOVE_GENERIC_USER_ACTION = 'REMOVE_GENERIC_USER_ACTION';

// remove user from generic list
export const REMOVE_SPECIFIC_USER_ACTION = 'REMOVE_SPECIFIC_USER_ACTION';
